// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMfgvUdM1qZ6WzrprmtjtcL53ncEAYn7I',
    appId: '1:920913460491:web:972760aba7752ad257f60e',
    messagingSenderId: '920913460491',
    projectId: 'salam-salam-8258c',
    authDomain: 'salam-salam-8258c.firebaseapp.com',
    databaseURL: 'https://salam-salam-8258c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'salam-salam-8258c.appspot.com',
    measurementId: 'G-S0BVYT33WY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR0eJRHkAND1NYw42L4PDKxrBDDk7372k',
    appId: '1:920913460491:android:f2958eb39ef9667857f60e',
    messagingSenderId: '920913460491',
    projectId: 'salam-salam-8258c',
    databaseURL: 'https://salam-salam-8258c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'salam-salam-8258c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOKigNW6PsSeG1wDdi1l_BzNB4kVwSgm8',
    appId: '1:920913460491:ios:3f85f85064850ddf57f60e',
    messagingSenderId: '920913460491',
    projectId: 'salam-salam-8258c',
    databaseURL: 'https://salam-salam-8258c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'salam-salam-8258c.appspot.com',
    iosClientId: '920913460491-a0ob3alvfp3begl8g1ghddn1kpecop79.apps.googleusercontent.com',
    iosBundleId: 'com.example.salamSalam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOKigNW6PsSeG1wDdi1l_BzNB4kVwSgm8',
    appId: '1:920913460491:ios:3f85f85064850ddf57f60e',
    messagingSenderId: '920913460491',
    projectId: 'salam-salam-8258c',
    databaseURL: 'https://salam-salam-8258c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'salam-salam-8258c.appspot.com',
    iosClientId: '920913460491-a0ob3alvfp3begl8g1ghddn1kpecop79.apps.googleusercontent.com',
    iosBundleId: 'com.example.salamSalam',
  );
}
